In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
from pathlib import Path

# in jupyter (lab / notebook), based on notebook path
module_path = str(Path.cwd().parents[0] / "src")
# in standard python

if module_path not in sys.path:
    sys.path.append(module_path)

In [3]:
import data_processing as dp
import case_study_all_accnts

In [4]:
# pip install sklearn
connector = dp.establish_connection()

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Going to open: https://newrelic.okta.com/app/snowflake/exkugjs4xeGHw0Vo10x7/sso/saml?SAMLRequest=lZJfb9owFMW%2FSuQ9Jzb%2FtmABFSvqysQ6VAJa92aSC%2FXi2MHXIWk%2F%2FRwoUzeplfZm2efc%2B%2FM9d3TVFCo4gkVp9Jh0IkYC0KnJpN6PyTq5CWMSoBM6E8poGJMnQHI1GaEoVMmnlXvU93CoAF3gC2nk7cOYVFZzI1Ai16IA5C7lq%2Bm3Be9GjAtEsM63I68s5fue0hpnUqMulgylx3t0ruSU1nUd1b3I2D3tMsYoG1KvaiUfLvrG%2F%2BkNfYeyfqv3Ci9fvjT6LPV5BO9Rbc8i5LdJsgyX31cJCaaX310bjVUBdgX2KFNY3y%2FOAOgJNNQWlEw9QpgJJwxGqE29UyKH1BRl5XzZyJ%2FoDjKqzF76Yc1nY1LmMvtqF4lyD73nvNLqbvMDjnqTNOL4cCiHKxnn68Pzdq0P8%2BE2TkmwuUTbbaOdI1Yw122gzl%2Bx7iBkH0PWT1jMBz3O4igedH%2BSYOYDlVq4k%2FNf6sjkTpzoRFnSP%2BAUmrza%2F8J%2BA19ua7YxHdZ8ooiGtgGT887wE4Gd%2FPckRvS1%2FWX%2F7nwk89nS%2BAJPwY2xhXBvJ9aJOqcbmYW7k5RDIaSaZpkFRJ%2BcUqa%2BtiCcX3NnKyB0cu7696JPfgM%3D&RelayState=ver%3A1-hint%3A33093663650894582-ETMsDgAAAZc6JPB0ABRBRVMvQ0JDL1BLQ1M1UGFkZGluZwEAABAAECxAKBJD6WAXdFlOZJ1HsDQAAACQ5S4S1t7fSQ%2FR%2FoTz6wpQ0IfcDNaJxhGlSv6qC5b9S329ZwTfWO%2Bxc5ruDNTqY6cqbzN7uVidQ7bIFSlTclrMVT3Dt2XXqLbziwcgMCl43yiRCqKZOQrxjdpsW52B6LVLKZ0H7vnkpDkmOcdbnZ9wZjMatv%2BKsei6TrzsDe6n89sxnxS2Q8J%2F8Fn17n8DS%2FeZABSSDgbCpKzzrv%2BUsp%2FqE1nzMCIYtA%3D%3D to authenticate...

In [5]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [57]:
# Pull data from Snowflake using raw_query
query = case_study_all_accnts.query()
df = dp.fetch_data(query, connector)

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Going to open: https://newrelic.okta.com/app/snowflake/exkugjs4xeGHw0Vo10x7/sso/saml?SAMLRequest=lZJRb9owFIX%2FSuQ9J3ZSGJ1FqAKUlYm2UUk7bW9uckkNiZ35Og399zOhTN2kVprkB8s%2B5%2Fq7Pnd8sa8r7xkMSq1iEgaMeKByXUhVxuQ%2BW%2FjnxEMrVCEqrSAmL4DkYjJGUVcNT1r7pO7gVwtoPVdIIe8vYtIaxbVAiVyJGpDbnK%2BT6xWPAsYbo63OdUXeWD52CEQw1hGeLAVKh%2FdkbcMp7bou6M4CbUoaMcYo%2B0Kd6iD5dNLvXU%2Fv6EPKBge9Uzh5%2Bso2ler4BR9hPR5FyK%2ByLPXT23VGvOSEOtMK2xrMGsyzzOH%2BbnUEQEegoDNQydwh%2BIWwQmOASnebSuwg13XTWlc2cDu6gYJWupSu8%2BU8Js1OFgmOSsWmN1scfc%2Bj9kd6uQJcpGE%2ByOaP9W42vS3X22i4%2FdZd5sR7OEUbHaJdIrawVIdArTti0dBnn302yMJzPnDrLIii4U%2FizV2gUgnbO%2F%2BlDvTOip5ONA39A05hv2vLLQ728PWqYw86ZPsRRdT0EDA5zgzvCczkv39iTN%2FaX%2BfvxkWynKfaFXjxFtrUwr6fWBiE%2FYks%2FE0v5VALWSVFYQDRJVdVupsZENaNuTUtEDo5vvr3oE9%2BAw%3D%3D&RelayState=ver%3A1-hint%3A33093663650894582-ETMsDgAAAZc8RjPZABRBRVMvQ0JDL1BLQ1M1UGFkZGluZwEAABAAEDl5X8x9eyBWGafSsYUzDGEAAACQKqEGOvY%2FXqGCF4n5YBF%2F9ZDCgTSfx97oLZSnlfbHrNbTuK3nbzYD%2FbtJsE6IStn5J6t5OFyXgWLPKf%2B%2F1se0PlQAXLRkVJpIaSscmc8TS%2FysoNxagmEokcPljyF8KtonCHSOuiTRfNdIWgpvKOfVCWkToZFGsp%2FOyWVbhw0jaUC6YTBiBab6%2Bu0D6eVE88PlABTrcAE4a25sQZvwg%2B9CEPwkHzB1tQ%3D%3D to authenticate...

In [58]:
df.head()

,ACCNT_AGE_MTHS,SUBSCRIPTION_ACCOUNT_ID,EFFECTIVE_SUBSCRIPTION_ACCOUNT_ID,SFDC_ACCOUNT_ID,SFDC_ACCOUNT_NAME,REPORT_AS_OF_DT,REPORT_MONTH,BUYING_PROGRAM,LATEST_BUYING_PROGRAM,EFFECTIVE_ACR,IS_CONTRACT_FLAG,LATEST_EFFECTIVE_ACR,BCM,LATEST_BCM,INGEST_BCM,INGEST_UNIT_PRICE,CCU_BCM,CCU_UNIT_PRICE,USERS_BCM,USERS_UNIT_PRICE,SUBSCRIPTION_TERM_START_DATE,SUBSCRIPTION_TERM_END_DATE,RENEWAL_DATE,MULTIYEAR_FLAG,TOTAL_ACR,INDUSTRY,PHYSICAL_COUNTRY,SALES_HIER_GEO,SALES_HIER_REGION,SALES_HIER_SUB_REGION,EMPLOYEES,CHURN_INDICATOR,CONTRACT_START_DATE,MONTHS_SINCE_CONTRACT_START,DAILY_ENGAGED_USERS,DAU_R7D,COMMITTED_USERS,ROLLING_60_DAY_MEDIAN,DENOM_USERS,ADV_USED_FEATURES,TOTAL_ADV_FEATURES,DAU_ACTUALS,USED_FEATURES,TOTAL_FEATURES_3_PERCENT,DAU_R30D,TOTAL_FEATURES_R7D,USED_FEATURES_R7D,L3M_BCM,DAY_WISE_ACR,MONTH_WISE_ACR,AMOUNT_LEFT,CTD_CONSUMPTION_AMT_UPDATED,DAY_TEMPERATURE,MONTH_TEMPERATURE,DAYS_TO_DEPLETE,MONTHS_TO_DEPLETE,DAYS_UNTIL_RENEWAL,MONTHS_UNTIL_RENEWAL,FIRST_REPORT_DATE,RENEWAL_URGENCY_DAYS,OVERAGES,REVENUE_GROWTH_SCORE,CONTRACT_LENGTH_MTHS,CTD_CONSUMPTION_AMT,QTD_CONSUMPTION_AMT,YTD_CONSUMPTION_AMT,MTD_CONSUMPTION_EFF_AMT,MIN_COMMIT_AMT,M_PLUS_1_BCM,M_PLUS_3_BCM,M_PLUS_4_BCM,M_PLUS_5_BCM,M_PLUS_6_BCM,M_PLUS_10_BCM,M_PLUS_11_BCM,M_PLUS_12_BCM,TARGET_M_PLUS_6_BCM,TARGET_M_PLUS_12_BCM,PCT_M_PLUS_1_BCM,PCT_M_PLUS_3_BCM,PCT_M_PLUS_6_BCM,PCT_M_PLUS_12_BCM,CONSUMED_MONTH_NUMBER,CONSUMED_MONTH_NUMBER_PER_SUBSCRIPTION,MTH_DIFF,MTHS_TILL_DATE,NUMBER_OF_OPEN_INVOICES_DUE_BEFORE_MONTH_END,METRIC_NAME,METRIC_VALUE,SCORE_TYPE,METRIC_SCORE,METRIC_NAME_SCORE,WEIGHTS,ADOPTION_SCORE_CAL,ENGAGEMENT_SCORE_CAL,FINANCIAL_HEALTH_SCORE_CAL,RISK_SCORE_CAL,SEGMENT_NAME
0,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2023-04-30,2023-04-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2022-11-21,2023-11-21,2023-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2022-11-21,5.0,17.000000000,17.000000000000,26.000000000,17.000000000000,26.000000000000,NaN,NaN,0,0,NaN,0.000,None,0.000,9556.000,313.249315068493,9528.000000000000,66612.252080729,47723.747919271,30.51,1.00,201.671971179924,6.970725416569,205.0,7.0,2023-11-21,None,None,50.00,12.00,47723.747919271,9528.000000000,9528.000000000,6909.843270842,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000000,9528.000000000000,0E-12,0E-12,0E-12,0E-12,5,5,5.0,26,0.00,PCT_P1_CASES,None,Risk_score,100.0,PCT_P1_CASES_HSCORE,0,20,0,69,100,Late Volume Plan
1,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2023-04-30,2023-04-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2022-11-21,2023-11-21,2023-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2022-11-21,5.0,17.000000000,17.000000000000,26.000000000,17.000000000000,26.000000000000,NaN,NaN,0,0,NaN,0.000,None,0.000,9556.000,313.249315068493,9528.000000000000,66612.252080729,47723.747919271,30.51,1.00,201.671971179924,6.970725416569,205.0,7.0,2023-11-21,None,None,50.00,12.00,47723.747919271,9528.000000000,9528.000000000,6909.843270842,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000000,9528.000000000000,0E-12,0E-12,0E-12,0E-12,5,5,5.0,26,0.00,RESOLUTION_RATE,None,Risk_score,100.0,RESOLUTION_RATE_HSCORE,0,20,0,69,100,Late Volume Plan
2,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2024-06-30,2024-06-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2023-11-21,2024-11-21,2024-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2023-11-21,7.0,20.000000000,20.000000000000,26.000000000,20.000000000000,26.000000000000,2.0,11.0,0,0,28.0,0.533,28.000,1.285,9528.000,312.393442622951,9528.000000000000,38112.000000000,76224.000000000,30.50,1.00,118.618113912232,4.000000000000,144.0,5.0,2023-11-21,None,None,31.00,12.00,69871.996824000,28584.000000000,28584.000000000,6481.279924563,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,None,9528.000000000000,None,0E-12,0E-12,0E-12,-100.000000000000,19,8,7.0,12,0.00,PRODUCT_STICKINESS_RATIO,18.18,Adoption_score,14.0,PRODUCT_STICKINESS_RATIO_HSCORE,0,23,0,64,100,Late Volume Plan
3,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2024-03-31,2024-03-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2023-11-21,2024-11-21,2024-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2023-11-21,4.0,20.000000000,20.000000000000,26.000000000,20.000000000000,26.000000000000,2.0,11.0,0,0,27.0,1.133,27.000,1.714,9528.000,312.393442622951,9528.000000000000,66696.000000000,47640.000000000,30.50,1.00,205.092250922509,7.000000000000,235.0,8.0,2023-11-21,None,None,31.00,12.00,41287.996824000,28584.000000000,114336.000000000,6713.377107505,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000000,9528.000000000000,0E-12,0E-12,0E-12,0E-12,16,5,4.0,15,0.00,OPEN_TICKETS,None,Engagement_score,0.0,OPEN_TICKETS_HSCORE,0,30,0,64,100,Late Volume Plan
4,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2025-06-02,2025-06-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2024-11-21,2025-11-21,2025-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2024-11-21,7.0,17.000000000,17.714285714285,26.000000000,18.000000000000,26.000000000000,NaN,NaN,0,0,41.0,0.066,41.714,0.000,9528.000,313.249315068493,9528.000000000000,38112.000000000,76224.000000000,30.42,1.00,118.618113912232,4.000000000000,172.0,5.0,2023-11-21,None,None,31.00,12.00,74318.400000000,23689.051786098,23689.051786098,4633.051786098,9528.000000000,None,None,None,None,None,None,None,None,None,None,-100.000000000000,-100.000000000000,-100.000000000000,-100.000000000000,31,8,7.0,0,None,ENGAGEMENT_SCORE,1.00,Engagement_score,100.0,ENGAGEMENT_SCORE_HSCORE,0,14,33,64,100,Late Volume Plan

In [59]:
df.shape

(272726, 98)

In [60]:
unique_combinations = df[['SFDC_ACCOUNT_NAME', 'SEGMENT_NAME']].drop_duplicates()
unique_combinations

                                  SFDC_ACCOUNT_NAME       SEGMENT_NAME
0                                 Hawaiian Airlines   Late Volume Plan
589                                         AON PLC  Late Savings Plan
1178                                 Filevine, Inc.  Late Savings Plan
1767                                     Taulia LLC  Late Savings Plan
2356                       ISN Software Corporation   Late Volume Plan
...                                             ...                ...
269781                                    Gainsight  Late Savings Plan
270370  Warner Media Customer POA Partnership Owner  Late Savings Plan
270959                               AlayaCare Inc.  Late Savings Plan
271548                                  Bestow Inc.  Late Savings Plan
272137                              VWR Corporation  Late Savings Plan

[501 rows x 2 columns]

In [61]:
df['SEGMENT_NAME'].unique()

array(['Late Volume Plan', 'Late Savings Plan', 'Early Savings Plan',
       'Early Volume Plan'], dtype=object)

In [62]:
score_cols = [
    "FINANCIAL_HEALTH_SCORE_CAL",
    "ADOPTION_SCORE_CAL",
    "ENGAGEMENT_SCORE_CAL",
    "RISK_SCORE_CAL"
]
df['OVERALL_HEALTH_SCORE'] = df[score_cols].mean(axis=1)

In [68]:
df['REPORT_MONTH'] = pd.to_datetime(df['REPORT_MONTH'])
df = df[df['REPORT_MONTH'] < pd.to_datetime('2024-12-01')]
df.head()

,ACCNT_AGE_MTHS,SUBSCRIPTION_ACCOUNT_ID,EFFECTIVE_SUBSCRIPTION_ACCOUNT_ID,SFDC_ACCOUNT_ID,SFDC_ACCOUNT_NAME,REPORT_AS_OF_DT,REPORT_MONTH,BUYING_PROGRAM,LATEST_BUYING_PROGRAM,EFFECTIVE_ACR,IS_CONTRACT_FLAG,LATEST_EFFECTIVE_ACR,BCM,LATEST_BCM,INGEST_BCM,INGEST_UNIT_PRICE,CCU_BCM,CCU_UNIT_PRICE,USERS_BCM,USERS_UNIT_PRICE,SUBSCRIPTION_TERM_START_DATE,SUBSCRIPTION_TERM_END_DATE,RENEWAL_DATE,MULTIYEAR_FLAG,TOTAL_ACR,INDUSTRY,PHYSICAL_COUNTRY,SALES_HIER_GEO,SALES_HIER_REGION,SALES_HIER_SUB_REGION,EMPLOYEES,CHURN_INDICATOR,CONTRACT_START_DATE,MONTHS_SINCE_CONTRACT_START,DAILY_ENGAGED_USERS,DAU_R7D,COMMITTED_USERS,ROLLING_60_DAY_MEDIAN,DENOM_USERS,ADV_USED_FEATURES,TOTAL_ADV_FEATURES,DAU_ACTUALS,USED_FEATURES,TOTAL_FEATURES_3_PERCENT,DAU_R30D,TOTAL_FEATURES_R7D,USED_FEATURES_R7D,L3M_BCM,DAY_WISE_ACR,MONTH_WISE_ACR,AMOUNT_LEFT,CTD_CONSUMPTION_AMT_UPDATED,DAY_TEMPERATURE,MONTH_TEMPERATURE,DAYS_TO_DEPLETE,MONTHS_TO_DEPLETE,DAYS_UNTIL_RENEWAL,MONTHS_UNTIL_RENEWAL,FIRST_REPORT_DATE,RENEWAL_URGENCY_DAYS,OVERAGES,REVENUE_GROWTH_SCORE,CONTRACT_LENGTH_MTHS,CTD_CONSUMPTION_AMT,QTD_CONSUMPTION_AMT,YTD_CONSUMPTION_AMT,MTD_CONSUMPTION_EFF_AMT,MIN_COMMIT_AMT,M_PLUS_1_BCM,M_PLUS_3_BCM,M_PLUS_4_BCM,M_PLUS_5_BCM,M_PLUS_6_BCM,M_PLUS_10_BCM,M_PLUS_11_BCM,M_PLUS_12_BCM,TARGET_M_PLUS_6_BCM,TARGET_M_PLUS_12_BCM,PCT_M_PLUS_1_BCM,PCT_M_PLUS_3_BCM,PCT_M_PLUS_6_BCM,PCT_M_PLUS_12_BCM,CONSUMED_MONTH_NUMBER,CONSUMED_MONTH_NUMBER_PER_SUBSCRIPTION,MTH_DIFF,MTHS_TILL_DATE,NUMBER_OF_OPEN_INVOICES_DUE_BEFORE_MONTH_END,METRIC_NAME,METRIC_VALUE,SCORE_TYPE,METRIC_SCORE,METRIC_NAME_SCORE,WEIGHTS,ADOPTION_SCORE_CAL,ENGAGEMENT_SCORE_CAL,FINANCIAL_HEALTH_SCORE_CAL,RISK_SCORE_CAL,SEGMENT_NAME,OVERALL_HEALTH_SCORE
0,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2023-04-30,2023-04-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2022-11-21,2023-11-21,2023-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2022-11-21,5.0,17.000000000,17.000000000000,26.000000000,17.000000000000,26.000000000000,NaN,NaN,0,0,NaN,0.000,None,0.000,9556.000,313.249315068493,9528.000000000000,66612.252080729,47723.747919271,30.51,1.00,201.671971179924,6.970725416569,205.0,7.0,2023-11-21,None,None,50.00,12.00,47723.747919271,9528.000000000,9528.000000000,6909.843270842,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000000,9528.000000000000,0E-12,0E-12,0E-12,0E-12,5,5,5.0,26,0.00,PCT_P1_CASES,None,Risk_score,100.0,PCT_P1_CASES_HSCORE,0,20,0,69,100,Late Volume Plan,47.25
1,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2023-04-30,2023-04-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2022-11-21,2023-11-21,2023-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2022-11-21,5.0,17.000000000,17.000000000000,26.000000000,17.000000000000,26.000000000000,NaN,NaN,0,0,NaN,0.000,None,0.000,9556.000,313.249315068493,9528.000000000000,66612.252080729,47723.747919271,30.51,1.00,201.671971179924,6.970725416569,205.0,7.0,2023-11-21,None,None,50.00,12.00,47723.747919271,9528.000000000,9528.000000000,6909.843270842,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000000,9528.000000000000,0E-12,0E-12,0E-12,0E-12,5,5,5.0,26,0.00,RESOLUTION_RATE,None,Risk_score,100.0,RESOLUTION_RATE_HSCORE,0,20,0,69,100,Late Volume Plan,47.25
2,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2024-06-30,2024-06-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2023-11-21,2024-11-21,2024-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2023-11-21,7.0,20.000000000,20.000000000000,26.000000000,20.000000000000,26.000000000000,2.0,11.0,0,0,28.0,0.533,28.000,1.285,9528.000,312.393442622951,9528.000000000000,38112.000000000,76224.000000000,30.50,1.00,118.618113912232,4.000000000000,144.0,5.0,2023-11-21,None,None,31.00,12.00,69871.996824000,28584.000000000,28584.000000000,6481.279924563,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,None,9528.000000000000,None,0E-12,0E-12,0E-12,-100.000000000000,19,8,7.0,12,0.00,PRODUCT_STICKINESS_RATIO,18.18,Adoption_score,14.0,PRODUCT_STICKINESS_RATIO_HSCORE,0,23,0,64,100,Late Volume Plan,46.75
3,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2024-03-31,2024-03-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2023-11-21,2024-11-21,2024-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2023-11-21,4.0,20.000000000,20.000000000000,26.000000000,20.000000000000,26.000000000000,2.0,11.0,0,0,27.0,1.133,27.000,1.714,9528.000,312.393442622951,9528.000000000000,66696.000000000,47640.000000000,30.50,1.00,205.092250922509,7.000000000000,235.0,8.0,2023-11-21,None,None,31.00,12.00,41287.996824000,28584.000000000,114336.000000000,6713.377107505,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000000,9528.000000000000,0E-12,0E-12,0E-12,0E-12,16,5,4.0,15,0.00,OPEN_TICKETS,None,Engagement_score,0.0,OPEN_TICKETS_HSCORE,0,30,0,64,100,Late Volume Plan,48.50
6,31,119372,119372,0011U00001S92ilQAB,Hawaiian Airlines,2024-11-30,2024-11-01,Volume Plan,Volume Plan,114336.000000000,1,114336.000000000,9528.000000000,9528.000000000,2508.000000000,0.300000000,0E-9,0E-9,7020.000000000,270.000000000,2024-11-21,2025-11-21,2025-11-21,0.0,114336.000000000,Transportation,United States,AMER,Enterprise,West,5001.000000000,N,2024-11-21,0.0,23.000000000,23.000000000000,26.000000000,23.000000000000,26.000000000000,3.0,11.0,0,0,39.0,1.566,39.000,4.285,9528.000,313.249315068493,9528.000000000000,104808.000000000,9528.000000000,30.42,1.00,326.199813258637,11.000000000000,356.0,12.0,2023-11-21,None,None,31.00,12.00,7622.400000000,19056.000000000,76224.000000000,7253.685753324,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,9528.000000000,None,None,None,9528.000000000000,None,0E-12,0E-12,0E-12,-100.000000000000,24,1,0.0,7,0.00,PRODUCT_UTILIZATION_RATE,10.99,Adoption_score,28.0,PRODUCT_UTILIZATION_RATE_HSCORE,0,34,33,64,89,Late Volume Plan,55.00

In [69]:
# Calculate time-ordered correlation for each account
correlation_data = []

for account in df['SUBSCRIPTION_ACCOUNT_ID'].unique():
    # Get account data and sort by date
    account_data = df[df['SUBSCRIPTION_ACCOUNT_ID'] == account].sort_values('REPORT_AS_OF_DT')
    
    # Only calculate if we have enough data points
    if len(account_data) >= 3:
        correlation = account_data['OVERALL_HEALTH_SCORE'].corr(account_data['PCT_M_PLUS_6_BCM'])
        
        correlation_data.append({
            'SUBSCRIPTION_ACCOUNT_ID': account,
            'SFDC_ACCOUNT_NAME': account_data['SFDC_ACCOUNT_NAME'].iloc[0],
            'Correlation': correlation,
            'Data_Points': len(account_data),
            'Date_Range': f"{account_data['REPORT_AS_OF_DT'].min()} to {account_data['REPORT_AS_OF_DT'].max()}"
        })

# Create DataFrame and sort by correlation
correlation_df = pd.DataFrame(correlation_data)
correlation_df = correlation_df.sort_values('Correlation', ascending=False)
correlation_df = correlation_df.reset_index(drop=True)

# Round correlation to 3 decimal places
correlation_df['Correlation'] = correlation_df['Correlation'].round(3)

# Display the results with date range information
display(correlation_df)

/Users/rchhetri/Library/Python/3.9/lib/python/site-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/rchhetri/Library/Python/3.9/lib/python/site-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

,SUBSCRIPTION_ACCOUNT_ID,SFDC_ACCOUNT_NAME,Correlation,Data_Points,Date_Range
0,2416082,SirsiDynix,0.874,456,2022-12-31 to 2024-11-30
1,4432444,Highspot,0.762,95,2024-07-31 to 2024-11-30
2,2324092,HHS/CMS/OEDA - (GDIT),0.745,456,2022-12-31 to 2024-11-30
3,1629146,"McCormick & Company, Incorporated",0.736,456,2022-12-31 to 2024-11-30
4,3124988,State of Arizona - Arizona Health Care Cost Co...,0.704,456,2022-12-31 to 2024-11-30
...,...,...,...,...,...
502,CC-0001531108,GE Healthcare,NaN,19,2024-11-30 to 2024-11-30
503,3641578,"Texas Roadhouse, Inc.",NaN,38,2022-12-31 to 2023-01-31
504,4740995,Cognitran Ltd.,NaN,19,2024-10-31 to 2024-10-31
505,3203252,Inmar Inc,NaN,57,2022-12-31 to 2023-02-28
506,1456545,"Hallmark Cards, Inc.",NaN,57,2022-12-31 to 2023-02-28

In [70]:
correlation_df.head(10)

,SUBSCRIPTION_ACCOUNT_ID,SFDC_ACCOUNT_NAME,Correlation,Data_Points,Date_Range
0,2416082,SirsiDynix,0.874,456,2022-12-31 to 2024-11-30
1,4432444,Highspot,0.762,95,2024-07-31 to 2024-11-30
2,2324092,HHS/CMS/OEDA - (GDIT),0.745,456,2022-12-31 to 2024-11-30
3,1629146,"McCormick & Company, Incorporated",0.736,456,2022-12-31 to 2024-11-30
4,3124988,State of Arizona - Arizona Health Care Cost Co...,0.704,456,2022-12-31 to 2024-11-30
5,661978,Drizly Inc,0.685,418,2022-12-31 to 2024-09-30
6,1440125,"Anaplan, Inc. (NYSE: PLAN)",0.679,456,2022-12-31 to 2024-11-30
7,180603,Bed Bath & Beyond Inc.,0.665,304,2022-12-31 to 2024-03-31
8,290409,Cornershop,0.645,342,2022-12-31 to 2024-05-31
9,2099792,"TCGplayer, Inc",0.643,456,2022-12-31 to 2024-11-30

In [71]:
correlation_df.head(6)['SUBSCRIPTION_ACCOUNT_ID'].tolist()

['2416082', '4432444', '2324092', '1629146', '3124988', '661978']

In [55]:
correlation_df [ correlation_df['SUBSCRIPTION_ACCOUNT_ID'] == '478028' ]

,SUBSCRIPTION_ACCOUNT_ID,SFDC_ACCOUNT_NAME,Correlation,Data_Points,Date_Range
83,478028,"AMC Entertainment Holdings, Inc.",-0.33,589,2022-12-31 00:00:00 to 2025-06-02 00:00:00